#!/bin/bash
#
# Fill the cask template's version and sha256 for a published release and write the result for
# the tap.
#
#   packaging/homebrew/update_cask.sh [--version X.Y.Z] [--zip PATH | --sha256 HEX] [--out FILE]
#
#   --version   release version (default: VERSION at the repo root)
#   --zip       hash this local zip instead of downloading the release asset
#   --sha256    use this checksum as given
#   --out       where to write the filled cask (default: stdout), e.g.
#               ../homebrew-tap/Casks/tokenamp.rb
#
# By default the zip is downloaded from the GitHub Release and hashed, and the hash is checked
# against the release's .sha256 asset. Hash what was published, not a local build: CI builds its
# own zip, and two builds of the same commit do not produce identical bytes.
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
TEMPLATE="$HERE/tokenamp.rb"
REPO="lobabobloblaw/tokenamp"

VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"
ZIP=""
SHA256=""
OUT=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --version) VERSION="${2:?--version needs a value}"; shift 2 ;;
        --zip) ZIP="${2:?--zip needs a path}"; shift 2 ;;
        --sha256) SHA256="${2:?--sha256 needs a value}"; shift 2 ;;
        --out) OUT="${2:?--out needs a path}"; shift 2 ;;
        *) echo "error: unknown option '$1'" >&2; exit 2 ;;
    esac
done

[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "error: version must be X.Y.Z (got '$VERSION')" >&2; exit 1; }

if [[ -z "$SHA256" && -n "$ZIP" ]]; then
    SHA256="$(shasum -a 256 "$ZIP" | cut -d ' ' -f 1)"
elif [[ -z "$SHA256" ]]; then
    NAME="Tokenamp-$VERSION.zip"
    URL="https://github.com/$REPO/releases/download/v$VERSION/$NAME"
    TMP="$(mktemp -d "${TMPDIR:-/tmp}/tokenamp-cask.XXXXXX")"
    trap 'rm -rf "$TMP"' EXIT
    echo "downloading $URL" >&2
    curl -fsSL -o "$TMP/$NAME" "$URL"
    curl -fsSL -o "$TMP/$NAME.sha256" "$URL.sha256"
    (cd "$TMP" && shasum -a 256 -c "$NAME.sha256" >&2)
    SHA256="$(shasum -a 256 "$TMP/$NAME" | cut -d ' ' -f 1)"
fi
SHA256="$(echo "$SHA256" | tr 'A-F' 'a-f')"
[[ "$SHA256" =~ ^[0-9a-f]{64}$ ]] || { echo "error: sha256 must be 64 hex digits (got '$SHA256')" >&2; exit 1; }

# Swap the template's header comment for a generated-file note, and replace the whole `version`
# and `sha256` lines; everything else is copied as is.
FILLED="$(
    echo "# Generated by packaging/homebrew/update_cask.sh in $REPO; edit the template there."
    awk 'body || !/^#/ { body = 1; print }' "$TEMPLATE" | sed -E \
        -e "s/^  version \".*\"$/  version \"$VERSION\"/" \
        -e "s/^  sha256 \".*\"$/  sha256 \"$SHA256\"/"
)"
grep -qF "  version \"$VERSION\"" <<< "$FILLED" || { echo "error: could not set version in $TEMPLATE" >&2; exit 1; }
grep -qF "  sha256 \"$SHA256\"" <<< "$FILLED" || { echo "error: could not set sha256 in $TEMPLATE" >&2; exit 1; }

if [[ -n "$OUT" ]]; then
    mkdir -p "$(dirname "$OUT")"
    printf '%s\n' "$FILLED" > "$OUT"
    echo "wrote $OUT (version $VERSION, sha256 $SHA256)" >&2
else
    printf '%s\n' "$FILLED"
fi
